# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
