# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.IntegerField()),
                ('colorid', models.IntegerField()),
                ('sizeid', models.IntegerField()),
                ('count', models.IntegerField()),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
    ]
